<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.trino.plugin</groupId>
        <artifactId>trino-web3</artifactId>
        <version>0.1-SNAPSHOT</version>
    </parent>

    <artifactId>trino-web3-plugin</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>io.trino.plugin</groupId>
            <artifactId>trino-web3-aptos</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.trino.plugin</groupId>
            <artifactId>trino-web3-adapter</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.trino.plugin</groupId>
            <artifactId>trino-web3-chain</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.trino.plugin</groupId>
            <artifactId>trino-web3-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.trino.plugin</groupId>
            <artifactId>trino-web3-evm</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.trino.plugin</groupId>
            <artifactId>trino-web3-runtime</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.trino</groupId>
            <artifactId>trino-spi</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.github.spotbugs</groupId>
            <artifactId>spotbugs-annotations</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>slice</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.airlift</groupId>
            <artifactId>units</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>assemble-plugin-distribution</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/assembly/plugin.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
